"""Campos del wire compartidos por captura, fuentes y clasificadores MQTT."""

NETWORK_COLUMNS = (
    'frame.time_delta', 'frame.time_delta_displayed', 'frame.time_relative',
    'frame.len', 'frame.cap_len', 'tcp.srcport', 'tcp.dstport',
)

CAPTURE_FIELDS = (
    'frame.time_delta',
    'frame.time_delta_displayed',
    'frame.time_epoch',
    'frame.time_invalid',
    'frame.time_relative',
    'ip.src',
    'ip.dst',
    'tcp.srcport',
    'tcp.dstport',
    'eth.src',
    'eth.dst',
    'frame.cap_len',
    'frame.coloring_rule.name',
    'frame.coloring_rule.string',
    'frame.comment',
    'frame.comment.expert',
    'frame.encap_type',
    'frame.file_off',
    'frame.ignored',
    'frame.incomplete',
    'frame.interface_id',
    'frame.interface_name',
    'frame.len',
    'frame.link_nr',
    'frame.marked',
    'frame.md5_hash',
    'frame.number',
    'frame.offset_shift',
    'mqtt.clientid',
    'mqtt.clientid_len',
    'mqtt.conack.flags',
    'mqtt.conack.flags.reserved',
    'mqtt.conack.flags.sp',
    'mqtt.conack.val',
    'mqtt.conflag.cleansess',
    'mqtt.conflag.passwd',
    'mqtt.conflag.qos',
    'mqtt.conflag.reserved',
    'mqtt.conflag.retain',
    'mqtt.conflag.uname',
    'mqtt.conflag.willflag',
    'mqtt.conflags',
    'mqtt.dupflag',
    'mqtt.hdrflags',
    'mqtt.kalive',
    'mqtt.len',
    'mqtt.msg',
    'mqtt.msgid',
    'mqtt.msgtype',
    'mqtt.passwd',
    'mqtt.passwd_len',
    'mqtt.proto_len',
    'mqtt.protoname',
    'mqtt.qos',
    'mqtt.retain',
    'mqtt.sub.qos',
    'mqtt.suback.qos',
    'mqtt.topic',
    'mqtt.topic_len',
    'mqtt.username',
    'mqtt.username_len',
    'mqtt.ver',
    'mqtt.willmsg',
    'mqtt.willmsg_len',
    'mqtt.willtopic',
    'mqtt.willtopic_len',
    'tcp.stream',
)

# Contexto (IP, identidad, stream) nunca entra en la matriz del modelo.
FEATURE_COLUMNS = tuple(c for c in CAPTURE_FIELDS
                        if c not in ('ip.src', 'ip.dst', 'tcp.stream'))
