"""Pure domain records used by the detector and its adapters."""

from dataclasses import dataclass

ALERT_KIND_CLASS = 'class'

'''
Represents the metadata of a client, in this case, 
a IoT device
'''
@dataclass(frozen=True, slots=True)
class ClientMeta:
    """Identity and endpoint information associated with an MQTT client."""
    client_id: str
    ip: str
    srcport: int
    dstport: int

'''
Represents a connection event, 
which is a record of a connection made by a client to 
the MQTT broker.
'''
@dataclass(frozen=True, slots=True)
class ConnectionEvent:
    """Record of a client CONNECT event observed at the broker."""
    ts: float
    client_id: str
    ip: str
    srcport: int
    dstport: int
    username: str | None = None
    anonymous: bool = False

'''
Represents the context of a captured frame: 
who sent it (client_id, IP or MAC) and on which ports/topic,
so an Alert can be enriched without a mutable side-channel.
'''
@dataclass(frozen=True, slots=True)
class FrameContext:
    """Metadata retained with a frame for alert enrichment."""
    ts: float | None = None
    client_id: str | None = None
    ip: str | None = None
    topic: str | None = None
    srcport: int = 0
    dstport: int = 0
    dst_ip: str | None = None
    stream_id: int | None = None
    eth_src: str | None = None
    eth_dst: str | None = None

'''
Represents an alert generated by the system, 
which can be of different kinds (DDos, Intrution, MiTM).
'''
@dataclass(frozen=True, slots=True)
class Alert:
    """Classification result emitted when a label is considered anomalous."""
    ts: float
    kind: str
    label: str
    client_id: str | None = None
    ip: str | None = None
    topic: str | None = None
    mse: float | None = None
    source: str | None = None

    def to_dict(self) -> dict:
        """Return the wire-format mapping used by alert sinks."""
        return {
            'ts': self.ts,
            'kind': self.kind,
            'label': self.label,
            'client_id': self.client_id,
            'ip': self.ip,
            'topic': self.topic,
            'mse': self.mse,
            'source': self.source,
        }
